#!/bin/bash
#SBATCH -J job # Job name (will be replaced by sbatch call: 'sbatch -J
'jobNameHere')
#SBATCH -c 4 # Cores requested
#SBATCH --mem 64G # Memory requested (in GB)
#SBATCH -t 3-00:00 # Days of runtime
#SBATCH -p gpu # Partition
#SBATCH --gres=gpu:1 # Requested specific type of GPU card
#SBATCH -e gpuLogs/%x_%j.out # %x = job name, %j = slurm job ID. Standard output goes
to this file
#SBATCH --mail-type=END # Send an email when the job ends
module load gcc/6.2.0 cuda/9.0 python/3.6.0
cd C:\Users\Sabatini Lab\Documents\GitHub\DeepLabCut
source Virtualenv/bin/activate
cd C:\Users\Sabatini Lab\Documents\GitHub\DeepLabCut\pose-tensorflow\models\reachingJan30-trainset95shuffle1\train
python3 C:\Users\Sabatini Lab\Documents\GitHub\DeepLabCut\pose-tensorflow\train.py
